export enum ActionType {
  CREATE_TASK_START = "create_task_start",
  CREATE_TASK_SUCCESS = "create_task_success",
  CREATE_TASK_ERROR = "create_task_error",
  DELETE_TASK_START = "delete_task_start",
  DELETE_TASK_SUCCESS = "delete_task_success",
  DELETE_TASK_ERROR = "delete_task_error",
  UPDATE_TASK_START = "update_task_start",
  UPDATE_TASK_SUCCESS = "update_task_success",
  UPDATE_TASK_ERROR = "update_task_error",
  AUTH_START = "auth_start",
  AUTH_SUCCESS = "auth_success",
  AUTH_ERROR = "auth_error",
  SIGNUP_START = "signup_start",
  SIGNUP_SUCCESS = "signup_success",
  SIGNUP_ERROR = "signup_error",
  SIGNOUT = "signout",
  RESET_TASKS = "reset_tasks",
  GET_TASKS_START = "get_tasks_start",
  GET_TASKS_SUCCESS = "get_tasks_success",
  GET_TASKS_ERROR = "get_tasks_error",
}
