#This is not pushed to a public repo in production projects, secrets are applied directly to k8s cluster for
#whatever infrastructure being used.
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: apps
type: Opaque
data:
  JWT_KEY: ZGhqaGVocmlqZGZua2Vyam9uamRmYnJpZXVvaW9qZGpmaW9qZGZta2RmZA==
  jwt-secret: dG9wU2VjcmV0NTE=
