apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pv-claim
  namespace: dbs
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
