#This is not pushed to a public repo in production projects, secrets are applied directly to k8s cluster for
#whatever infrastructure being used
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps #change to apps for microservice
type: Opaque
data:
  pg-root-username: dGVzdF91c2Vy
  pg-root-password: bXlzZWNyZXRwYXNzd29yZA==
  pgadmin-password: U3VwZXJTZWNyZXQ=
  pgadmin-email: ZGFyZS5mYWxvbGE3QGdtYWlsLmNvbQ==
