apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: #files to run with skaffold
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: damilare77/tasks
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
